#DataSource Configuration Properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: o9L2TtFd

  #Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

  #Error Stack trace
  error:
    include-stacktrace: never
    include-message: always

#Hibernate SQL Logging
logging:
  level:
    hibernate:
      SQL: DEBUG
  org:
    hibernate:
      type: TRACE

org:
  springframework:
    boot:
      web:
        server:
          WebServerException: Unable