server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoWorkers-Universitary-Residence/Microservices.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: "feature/gateway"
  security:
    user:
      name: root
      password: universitaryresidence
